### ISSUE TITLE
Suggestion: Close sidebar/TOC when a click/tap event occurs on the body

### ISSUE THREAD

**Issue by sdrothrock** [docura/docura#10]
I think the expected behavior for offcanvas sidebar/TOC is to have them close when the body is clicked, rather than having them open all the time.

Another benefit of this is that it's simpler for mobile users to close the sidebar/TOC as they don't have to reach to the top of the screen for the `x` button.

If you're ok with this, please let me know and I'll work on it.

**Comment by dumindu** [comment]
That was my initial intention as well; adding model class affect with glass background. But these days I am actively looking for Senior Go Backend opportunities and preparing and doing interview questions. So, in this side project, I was focusing only must have features.

**Comment by sdrothrock** [comment]
I completely understand focusing on the job hunt! If you don't mind this suggestion, I'll happily work on it when I have some time, too.

If you have other issues that have been hanging in your mind for a bit and also the time to write them up, I'll also try to work on those when I can.
