### ISSUE TITLE
Running Provided Command Lead to Not Found Page

### ISSUE THREAD

**Issue by ahmedmahmoud321** [docura/docura#12]
I have tried to run the theme using provided CLI commands but didn't seem to work, the theme looks awesome but the documentation not clear. 

```shell
hugo new site newsite
cd newsite
git init
git submodule add https://github.com/docura/docura.git themes/docura
rm config.toml && cp -r themes/docura/config .
echo "theme = 'docura'" >> config/_default/config.toml
hugo server
```

![image](https://github.com/docura/docura/assets/73083104/1a0a0550-e9bd-4aeb-a9cc-4ef0cb189382)

**Comment by dumindu** [comment]
- I tried to reproduce but no issue on my end to access http://localhost:1313/
- Make sure you use [Hugo extended version](https://gohugo.io/installation/). Those commands sync with [Hugo-Quick start](https://gohugo.io/getting-started/quick-start/#create-a-site). Make sure you face no issue without using the theme.
- If you get this issue on http://localhost:1313/docs/, you have to create your content pages under /docs first. Refer, https://docura.github.io/docs/first-documentation/

**Comment by ahmedmahmoud321** [comment]
yes, working now with [Hugo extended version](https://gohugo.io/installation/) 
```
# newer version of hugo use naming of hugo.toml 
rm config.toml && cp -r themes/docura/config .
```
