### ISSUE TITLE
how to add Documentation?

### ISSUE THREAD

**Issue by lightislost** [docura/docura#19]
when I use documation, url is http://localhost:1313/docs
it shows <Page Not Found>

how can I add the Documentation ?

**Comment by dumindu** [comment]
@lightislost Hope you already fixed this issue :)
Feel free to overwrite the theme variables like I did in https://github.com/docura/site/blob/main/assets/scss/theme/default.scss by adding assets/scss/theme/default.scss to your repo. 
Same way icons like in https://github.com/learning-cloud-native-go/learning-cloud-native-go.github.io/blob/pre-setup/assets/scss/icon/default.scss by adding assets/scss/icon/default.scss. Use https://yoksel.github.io/url-encoder/ to convert any SVG to icon class. Remember to set width='18' height='18' on css on icons. Currently I am using https://fonts.google.com/icons?icon.set=Material+Icons&icon.style=Two+tone (sadly, use chrome if you can't see icons on this page). I saw you are using translations. As I couldn't test those properly you may need some guild from Hugo docs and community on those. Feel free to buzz if you need any help on those later on.

**Comment by lightislost** [comment]
Thank you for your support. I have already resolved the issue by consulting Docura's documentation.
