### ISSUE TITLE
algolia How do I use it?

### ISSUE THREAD

**Issue by cnsync** [docura/docura#22]
Is algolia currently fully functional? I use hugo-algolia --config . /hugo.yaml to generate and upload an index, but I can't get the data correctly.

**Comment by dumindu** [comment]
Can you kindly double check your Algolia configuration to see if the selectors are correct? On their dashboard 

`lvl1: "article h1"`; should not be `lvl1: ".article h1",`

**Comment by dumindu** [comment]
And follow https://docura.github.io/docs/configurations/

**Comment by cnsync** [comment]
Ok, thanks for the answer, I'm checking to see if it's because of this problem

**Comment by cnsync** [comment]
docsearch.min.js:2  Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'lvl1')
    at docsearch.min.js:2:100961
    at docsearch.min.js:2:74980
    at Array.reduce (<anonymous>)
    at rr (docsearch.min.js:2:74952)
    at Object.getItems (docsearch.min.js:2:100924)
    at docsearch.min.js:2:38569
    at Array.map (<anonymous>)
    at docsearch.min.js:2:38527

**Comment by cnsync** [comment]
I'm using https://dashboard.algolia.com/ instead of docsearch

**Comment by dumindu** [comment]
1. Can you go to https://crawler.algolia.com/admin/crawlers login with same account
2. Click on your app and select Editor on left side
3. Please get a backup and save locally. After that search `recordProps` and check what is inside? 

This is some sample when using docsearch. You can check what's inside your app crawler
```
actions: [
    {
      indexName: "mysite",
      pathsToMatch: ["https://mysite.github.io/docs/**"],
      recordExtractor: ({ $, helpers }) => {
        return helpers.docsearch({
          recordProps: {
            lvl1: "article h1",
            content: "article p, article li",
            lvl0: {
              selectors: "",
              defaultValue: "Documentation",
            },
            lvl2: "article h2",
            lvl3: "article h3",
            lvl4: "article h4",
          },
          indexHeadings: false,
        });
      },
    },
  ],
```

Btw I've used docsearch only. You may need to get support from the algolia team/ support@algolia.com.

I am using https://github.com/docura/docura/blob/main/assets/js/component/docsearch.min.js , you may need to embed different js lib according to their suggestions

**Comment by dumindu** [comment]
If you wanna more mature ecosystem, 
- https://github.com/squidfunk/mkdocs-material
- https://github.com/shuding/nextra
