### ISSUE TITLE
Question: Left sidebar (sticky option)

### ISSUE THREAD

**Issue by LITUATUI** [docura/docura#9]
Is there an option to make the left sidebar sticky just like the right sidebar is?

Thanks!

**Comment by dumindu** [comment]
@LITUATUI Thanks for the interest for this theme. 

Docura is highly inspired from the simplicity of the [navy theme](https://github.com/hexojs/site/tree/master/themes/navy) of [Hexo](https://hexo.io/) docs and make the all items of the left sidebar visible was a design decision, as I personally believe it makes the pages/sections more visible/ accessible to the reader; plus it motivates readers to read more. But each section should use short but self-descriptive titles + a better separation of sections.

Ex. 
- https://gorm.io/docs/
- https://www.11ty.dev/docs/
- https://learning-rust.github.io/docs/overview/

So, I haven't add a config to make the left sidebar sticky, for the moment.

**Comment by LITUATUI** [comment]
Examples of good implementation of sticky left sidebar.

https://lotusdocs.dev/docs/overview/
https://gethinode.com/docs/getting-started/introduction/
https://course.naturecast.org/lessons/
https://www.docsy.dev/docs/

Sticky sidebars are great to make sure that there is no empty (wasted) space on the screen.

Maybe not as default, but as an option it would be great to have in your theme.

Anyway, your theme looks awesome, I'll be paying attention to it.

**Comment by dumindu** [comment]
@LITUATUI You can check the sticky-sidebar branch; https://github.com/docura/docura/tree/sticky-sidebar
Personally, I think this can create more issues instead of a complete solution as now sidebar items can overflow too much and need to make each sidebar section collapsable which is quite opposite of design decision to make the content more visible, as this theme support multiple docs sets.

**Comment by dumindu** [comment]
@LITUATUI After thoughtful consideration, made the left sidebar sticky as the default behavior.

**Comment by LITUATUI** [comment]
Thanks!

By the way is there an option to make the top navigation bar sticky as well?

**Comment by dumindu** [comment]
Hah ha. I am thinking how to remove it totally, to make focus to the
content.
